<h1>HELL ON NOSTR</h1>
<p>
    CREATE ANY ROOM WITH A NAME BY ADDING /ANYNAME TO THE END OF THIS URL.
    <br />
    EVERYONE CAN TALK
    <br />
    NOBODY OWNS A ROOM
    <br />
    ALL KEYS ARE RANDOMLY GENERATED
</p>